-- ============================================================
-- Project X - PostgreSQL / Supabase schema
-- ============================================================
-- Paste this file into Supabase SQL Editor and run it.
--
-- Notes:
-- - Uses UUIDs generated by pgcrypto.
-- - Uses Supabase auth.users for authenticated users.
-- - The public.users table mirrors the application's user profile.
-- - All timestamps use timestamptz.
-- ============================================================

begin;

create extension if not exists pgcrypto;

-- ============================================================
-- ENUM TYPES
-- ============================================================

do $$
begin
    create type public.project_status as enum (
        'planned',
        'active',
        'completed',
        'cancelled'
    );
exception
    when duplicate_object then null;
end $$;

do $$
begin
    create type public.goal_type as enum (
        'numeric',
        'boolean',
        'milestone'
    );
exception
    when duplicate_object then null;
end $$;

do $$
begin
    create type public.habit_frequency as enum (
        'daily',
        'weekly',
        'monthly'
    );
exception
    when duplicate_object then null;
end $$;

do $$
begin
    create type public.media_type as enum (
        'image',
        'video',
        'audio',
        'document'
    );
exception
    when duplicate_object then null;
end $$;

-- ============================================================
-- USERS
-- ============================================================
-- Supabase Auth is the source of truth for authentication.
-- id references auth.users(id).

create table if not exists public.users (
    id uuid primary key references auth.users(id) on delete cascade,
    username varchar(50) not null unique,
    email varchar(255) not null unique,
    display_name varchar(100),
    avatar_url text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

-- ============================================================
-- PROJECTS
-- ============================================================

create table if not exists public.projects (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references public.users(id) on delete cascade,
    name varchar(100) not null,
    description text,
    start_date date not null,
    end_date date not null,
    status public.project_status not null default 'planned',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint projects_dates_check
        check (end_date >= start_date)
);

-- ============================================================
-- CATEGORIES
-- ============================================================

create table if not exists public.categories (
    id uuid primary key default gen_random_uuid(),
    name varchar(50) not null unique,
    description text,
    icon varchar(50),
    is_default boolean not null default true,
    created_at timestamptz not null default now()
);

-- ============================================================
-- PROJECT <-> CATEGORY
-- ============================================================

create table if not exists public.project_categories (
    project_id uuid not null references public.projects(id) on delete cascade,
    category_id uuid not null references public.categories(id) on delete cascade,
    position integer not null default 0,

    primary key (project_id, category_id),

    constraint project_categories_position_check
        check (position >= 0)
);

-- ============================================================
-- GOALS
-- ============================================================

create table if not exists public.goals (
    id uuid primary key default gen_random_uuid(),
    project_id uuid not null references public.projects(id) on delete cascade,
    category_id uuid not null references public.categories(id) on delete restrict,

    title varchar(150) not null,
    description text,

    goal_type public.goal_type not null default 'numeric',
    unit varchar(30),

    minimum_value numeric,
    target_value numeric,
    bonus_value numeric,

    deadline date,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint goals_values_non_negative_check
        check (
            (minimum_value is null or minimum_value >= 0)
            and
            (target_value is null or target_value >= 0)
            and
            (bonus_value is null or bonus_value >= 0)
        ),

    constraint goals_target_order_check
        check (
            target_value is null
            or minimum_value is null
            or target_value >= minimum_value
        ),

    constraint goals_bonus_order_check
        check (
            bonus_value is null
            or target_value is null
            or bonus_value >= target_value
        )
);

-- ============================================================
-- GOAL LOGS
-- ============================================================

create table if not exists public.goal_logs (
    id uuid primary key default gen_random_uuid(),
    goal_id uuid not null references public.goals(id) on delete cascade,
    value numeric not null default 0,
    note text,
    logged_at timestamptz not null default now(),
    created_at timestamptz not null default now(),

    constraint goal_logs_value_check
        check (value >= 0)
);

-- ============================================================
-- HABITS
-- ============================================================

create table if not exists public.habits (
    id uuid primary key default gen_random_uuid(),
    project_id uuid not null references public.projects(id) on delete cascade,
    category_id uuid not null references public.categories(id) on delete restrict,

    name varchar(150) not null,
    description text,

    frequency public.habit_frequency not null default 'daily',
    target_count integer,

    unit varchar(30),

    start_date date not null,
    end_date date,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint habits_target_count_check
        check (target_count is null or target_count > 0),

    constraint habits_dates_check
        check (end_date is null or end_date >= start_date)
);

-- ============================================================
-- HABIT LOGS
-- ============================================================

create table if not exists public.habit_logs (
    id uuid primary key default gen_random_uuid(),
    habit_id uuid not null references public.habits(id) on delete cascade,
    date date not null,
    value numeric not null default 1,
    note text,
    created_at timestamptz not null default now(),

    constraint habit_logs_value_check
        check (value >= 0),

    constraint habit_logs_unique_day
        unique (habit_id, date)
);

-- ============================================================
-- MILESTONES
-- ============================================================

create table if not exists public.milestones (
    id uuid primary key default gen_random_uuid(),
    project_id uuid not null references public.projects(id) on delete cascade,

    title varchar(150) not null,
    description text,

    target_date date,
    completed_at timestamptz,

    created_at timestamptz not null default now()
);

-- ============================================================
-- JOURNAL ENTRIES
-- ============================================================

create table if not exists public.journal_entries (
    id uuid primary key default gen_random_uuid(),
    project_id uuid not null references public.projects(id) on delete cascade,

    title varchar(150),
    content text not null,

    mood smallint,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint journal_entries_mood_check
        check (mood is null or (mood between 1 and 10))
);

-- ============================================================
-- PROJECT CHECK-INS
-- ============================================================

create table if not exists public.project_checkins (
    id uuid primary key default gen_random_uuid(),
    project_id uuid not null references public.projects(id) on delete cascade,

    date date not null,

    mood smallint,
    energy smallint,
    motivation smallint,

    reflection text,

    created_at timestamptz not null default now(),

    constraint project_checkins_mood_check
        check (mood is null or (mood between 1 and 10)),

    constraint project_checkins_energy_check
        check (energy is null or (energy between 1 and 10)),

    constraint project_checkins_motivation_check
        check (motivation is null or (motivation between 1 and 10)),

    constraint project_checkins_unique_day
        unique (project_id, date)
);

-- ============================================================
-- MEDIA
-- ============================================================

create table if not exists public.media (
    id uuid primary key default gen_random_uuid(),

    user_id uuid not null references public.users(id) on delete cascade,
    project_id uuid not null references public.projects(id) on delete cascade,
    goal_id uuid references public.goals(id) on delete set null,

    type public.media_type not null,
    url text not null,

    title varchar(150),
    description text,

    created_at timestamptz not null default now()
);

-- ============================================================
-- ACHIEVEMENTS
-- ============================================================

create table if not exists public.achievements (
    id uuid primary key default gen_random_uuid(),

    name varchar(100) not null unique,
    description text not null,
    icon varchar(50),

    requirement_type varchar(50) not null,
    requirement_value numeric,

    created_at timestamptz not null default now()
);

-- ============================================================
-- USER ACHIEVEMENTS
-- ============================================================

create table if not exists public.user_achievements (
    user_id uuid not null references public.users(id) on delete cascade,
    achievement_id uuid not null references public.achievements(id) on delete cascade,
    project_id uuid references public.projects(id) on delete set null,

    unlocked_at timestamptz not null default now(),

    primary key (user_id, achievement_id)
);

-- ============================================================
-- PROJECT TEMPLATES
-- ============================================================

create table if not exists public.project_templates (
    id uuid primary key default gen_random_uuid(),

    name varchar(100) not null,
    description text,

    duration_days integer,

    created_by uuid references public.users(id) on delete set null,

    is_public boolean not null default false,

    created_at timestamptz not null default now(),

    constraint project_templates_duration_check
        check (duration_days is null or duration_days > 0)
);

-- ============================================================
-- NOTIFICATIONS
-- ============================================================

create table if not exists public.notifications (
    id uuid primary key default gen_random_uuid(),

    user_id uuid not null references public.users(id) on delete cascade,

    type varchar(50) not null,
    title varchar(150) not null,
    message text not null,

    scheduled_at timestamptz,
    read_at timestamptz,

    created_at timestamptz not null default now()
);

-- ============================================================
-- INDEXES
-- ============================================================

create index if not exists idx_projects_user_id
    on public.projects(user_id);

create index if not exists idx_projects_status
    on public.projects(status);

create index if not exists idx_projects_dates
    on public.projects(start_date, end_date);

create index if not exists idx_project_categories_category_id
    on public.project_categories(category_id);

create index if not exists idx_goals_project_id
    on public.goals(project_id);

create index if not exists idx_goals_category_id
    on public.goals(category_id);

create index if not exists idx_goal_logs_goal_id
    on public.goal_logs(goal_id);

create index if not exists idx_goal_logs_logged_at
    on public.goal_logs(logged_at);

create index if not exists idx_habits_project_id
    on public.habits(project_id);

create index if not exists idx_habits_category_id
    on public.habits(category_id);

create index if not exists idx_habit_logs_habit_id
    on public.habit_logs(habit_id);

create index if not exists idx_habit_logs_date
    on public.habit_logs(date);

create index if not exists idx_milestones_project_id
    on public.milestones(project_id);

create index if not exists idx_journal_entries_project_id
    on public.journal_entries(project_id);

create index if not exists idx_journal_entries_created_at
    on public.journal_entries(created_at);

create index if not exists idx_project_checkins_project_id
    on public.project_checkins(project_id);

create index if not exists idx_media_user_id
    on public.media(user_id);

create index if not exists idx_media_project_id
    on public.media(project_id);

create index if not exists idx_media_goal_id
    on public.media(goal_id);

create index if not exists idx_user_achievements_achievement_id
    on public.user_achievements(achievement_id);

create index if not exists idx_project_templates_created_by
    on public.project_templates(created_by);

create index if not exists idx_notifications_user_id
    on public.notifications(user_id);

create index if not exists idx_notifications_scheduled_at
    on public.notifications(scheduled_at);

-- ============================================================
-- UPDATED_AT TRIGGER
-- ============================================================

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists set_users_updated_at on public.users;
create trigger set_users_updated_at
before update on public.users
for each row execute function public.set_updated_at();

drop trigger if exists set_projects_updated_at on public.projects;
create trigger set_projects_updated_at
before update on public.projects
for each row execute function public.set_updated_at();

drop trigger if exists set_goals_updated_at on public.goals;
create trigger set_goals_updated_at
before update on public.goals
for each row execute function public.set_updated_at();

drop trigger if exists set_habits_updated_at on public.habits;
create trigger set_habits_updated_at
before update on public.habits
for each row execute function public.set_updated_at();

drop trigger if exists set_journal_entries_updated_at on public.journal_entries;
create trigger set_journal_entries_updated_at
before update on public.journal_entries
for each row execute function public.set_updated_at();

-- ============================================================
-- CREATE PUBLIC USER PROFILE AFTER SUPABASE AUTH SIGNUP
-- ============================================================
-- The application should provide username/display_name when
-- inserting into public.users, or this trigger can be extended
-- to read metadata from auth.users.

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
    insert into public.users (
        id,
        username,
        email,
        display_name,
        avatar_url
    )
    values (
        new.id,
        coalesce(
            new.raw_user_meta_data ->> 'username',
            split_part(new.email, '@', 1)
        ),
        new.email,
        new.raw_user_meta_data ->> 'display_name',
        new.raw_user_meta_data ->> 'avatar_url'
    )
    on conflict (id) do nothing;

    return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

-- ============================================================
-- DEFAULT CATEGORIES
-- ============================================================

insert into public.categories (name, description, icon, is_default)
values
    ('Create', 'Build and create things.', 'create', true),
    ('Learn', 'Learn and develop new knowledge.', 'book', true),
    ('Body', 'Physical health, fitness and performance.', 'activity', true),
    ('Expression', 'Creative expression such as art, music, writing or video.', 'palette', true),
    ('Experience', 'Discover, explore and experience new things.', 'compass', true),
    ('Social', 'Relationships, friendships and social development.', 'users', true),
    ('X', 'A completely personal category defined by the user.', 'sparkles', true)
on conflict (name) do nothing;

commit;


-- ============================================================
-- ROW LEVEL SECURITY (RLS)
-- ============================================================
-- Security model:
-- - Users can only read/update their own profile.
-- - Users can only access their own projects and data belonging
--   to those projects.
-- - Categories are readable by everyone, but only default/system
--   categories are protected from user-side writes.
-- - Public project templates can be read by everyone.
-- - Private templates are visible only to their creator.
-- - Achievements are readable by everyone.
-- - User achievements are private to the owning user.
-- - Notifications are private to the owning user.
-- ============================================================

-- Helper functions
create or replace function public.is_project_owner(p_project_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select exists (
        select 1
        from public.projects
        where id = p_project_id
          and user_id = auth.uid()
    );
$$;

create or replace function public.is_goal_owner(p_goal_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select exists (
        select 1
        from public.goals g
        join public.projects p on p.id = g.project_id
        where g.id = p_goal_id
          and p.user_id = auth.uid()
    );
$$;

create or replace function public.is_habit_owner(p_habit_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select exists (
        select 1
        from public.habits h
        join public.projects p on p.id = h.project_id
        where h.id = p_habit_id
          and p.user_id = auth.uid()
    );
$$;

-- ============================================================
-- ENABLE RLS
-- ============================================================

alter table public.users enable row level security;
alter table public.projects enable row level security;
alter table public.categories enable row level security;
alter table public.project_categories enable row level security;
alter table public.goals enable row level security;
alter table public.goal_logs enable row level security;
alter table public.habits enable row level security;
alter table public.habit_logs enable row level security;
alter table public.milestones enable row level security;
alter table public.journal_entries enable row level security;
alter table public.project_checkins enable row level security;
alter table public.media enable row level security;
alter table public.achievements enable row level security;
alter table public.user_achievements enable row level security;
alter table public.project_templates enable row level security;
alter table public.notifications enable row level security;

-- ============================================================
-- USERS POLICIES
-- ============================================================

drop policy if exists "Users can view own profile" on public.users;
create policy "Users can view own profile"
on public.users
for select
to authenticated
using (id = auth.uid());

drop policy if exists "Users can insert own profile" on public.users;
create policy "Users can insert own profile"
on public.users
for insert
to authenticated
with check (id = auth.uid());

drop policy if exists "Users can update own profile" on public.users;
create policy "Users can update own profile"
on public.users
for update
to authenticated
using (id = auth.uid())
with check (id = auth.uid());

drop policy if exists "Users can delete own profile" on public.users;
create policy "Users can delete own profile"
on public.users
for delete
to authenticated
using (id = auth.uid());

-- ============================================================
-- PROJECTS POLICIES
-- ============================================================

drop policy if exists "Users can view own projects" on public.projects;
create policy "Users can view own projects"
on public.projects
for select
to authenticated
using (user_id = auth.uid());

drop policy if exists "Users can create own projects" on public.projects;
create policy "Users can create own projects"
on public.projects
for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists "Users can update own projects" on public.projects;
create policy "Users can update own projects"
on public.projects
for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists "Users can delete own projects" on public.projects;
create policy "Users can delete own projects"
on public.projects
for delete
to authenticated
using (user_id = auth.uid());

-- ============================================================
-- CATEGORIES POLICIES
-- ============================================================

-- Categories are global/reference data.
drop policy if exists "Anyone can view categories" on public.categories;
create policy "Anyone can view categories"
on public.categories
for select
to anon, authenticated
using (true);

-- No INSERT/UPDATE/DELETE policy is intentionally provided.
-- Categories are managed by the backend/admin.

-- ============================================================
-- PROJECT CATEGORIES POLICIES
-- ============================================================

drop policy if exists "Users can view categories of own projects" on public.project_categories;
create policy "Users can view categories of own projects"
on public.project_categories
for select
to authenticated
using (public.is_project_owner(project_id));

drop policy if exists "Users can add categories to own projects" on public.project_categories;
create policy "Users can add categories to own projects"
on public.project_categories
for insert
to authenticated
with check (public.is_project_owner(project_id));

drop policy if exists "Users can update categories of own projects" on public.project_categories;
create policy "Users can update categories of own projects"
on public.project_categories
for update
to authenticated
using (public.is_project_owner(project_id))
with check (public.is_project_owner(project_id));

drop policy if exists "Users can remove categories from own projects" on public.project_categories;
create policy "Users can remove categories from own projects"
on public.project_categories
for delete
to authenticated
using (public.is_project_owner(project_id));

-- ============================================================
-- GOALS POLICIES
-- ============================================================

drop policy if exists "Users can view own goals" on public.goals;
create policy "Users can view own goals"
on public.goals
for select
to authenticated
using (public.is_project_owner(project_id));

drop policy if exists "Users can create own goals" on public.goals;
create policy "Users can create own goals"
on public.goals
for insert
to authenticated
with check (public.is_project_owner(project_id));

drop policy if exists "Users can update own goals" on public.goals;
create policy "Users can update own goals"
on public.goals
for update
to authenticated
using (public.is_project_owner(project_id))
with check (public.is_project_owner(project_id));

drop policy if exists "Users can delete own goals" on public.goals;
create policy "Users can delete own goals"
on public.goals
for delete
to authenticated
using (public.is_project_owner(project_id));

-- ============================================================
-- GOAL LOGS POLICIES
-- ============================================================

drop policy if exists "Users can view own goal logs" on public.goal_logs;
create policy "Users can view own goal logs"
on public.goal_logs
for select
to authenticated
using (public.is_goal_owner(goal_id));

drop policy if exists "Users can create own goal logs" on public.goal_logs;
create policy "Users can create own goal logs"
on public.goal_logs
for insert
to authenticated
with check (public.is_goal_owner(goal_id));

drop policy if exists "Users can update own goal logs" on public.goal_logs;
create policy "Users can update own goal logs"
on public.goal_logs
for update
to authenticated
using (public.is_goal_owner(goal_id))
with check (public.is_goal_owner(goal_id));

drop policy if exists "Users can delete own goal logs" on public.goal_logs;
create policy "Users can delete own goal logs"
on public.goal_logs
for delete
to authenticated
using (public.is_goal_owner(goal_id));

-- ============================================================
-- HABITS POLICIES
-- ============================================================

drop policy if exists "Users can view own habits" on public.habits;
create policy "Users can view own habits"
on public.habits
for select
to authenticated
using (public.is_project_owner(project_id));

drop policy if exists "Users can create own habits" on public.habits;
create policy "Users can create own habits"
on public.habits
for insert
to authenticated
with check (public.is_project_owner(project_id));

drop policy if exists "Users can update own habits" on public.habits;
create policy "Users can update own habits"
on public.habits
for update
to authenticated
using (public.is_project_owner(project_id))
with check (public.is_project_owner(project_id));

drop policy if exists "Users can delete own habits" on public.habits;
create policy "Users can delete own habits"
on public.habits
for delete
to authenticated
using (public.is_project_owner(project_id));

-- ============================================================
-- HABIT LOGS POLICIES
-- ============================================================

drop policy if exists "Users can view own habit logs" on public.habit_logs;
create policy "Users can view own habit logs"
on public.habit_logs
for select
to authenticated
using (public.is_habit_owner(habit_id));

drop policy if exists "Users can create own habit logs" on public.habit_logs;
create policy "Users can create own habit logs"
on public.habit_logs
for insert
to authenticated
with check (public.is_habit_owner(habit_id));

drop policy if exists "Users can update own habit logs" on public.habit_logs;
create policy "Users can update own habit logs"
on public.habit_logs
for update
to authenticated
using (public.is_habit_owner(habit_id))
with check (public.is_habit_owner(habit_id));

drop policy if exists "Users can delete own habit logs" on public.habit_logs;
create policy "Users can delete own habit logs"
on public.habit_logs
for delete
to authenticated
using (public.is_habit_owner(habit_id));

-- ============================================================
-- MILESTONES POLICIES
-- ============================================================

drop policy if exists "Users can view own milestones" on public.milestones;
create policy "Users can view own milestones"
on public.milestones
for select
to authenticated
using (public.is_project_owner(project_id));

drop policy if exists "Users can create own milestones" on public.milestones;
create policy "Users can create own milestones"
on public.milestones
for insert
to authenticated
with check (public.is_project_owner(project_id));

drop policy if exists "Users can update own milestones" on public.milestones;
create policy "Users can update own milestones"
on public.milestones
for update
to authenticated
using (public.is_project_owner(project_id))
with check (public.is_project_owner(project_id));

drop policy if exists "Users can delete own milestones" on public.milestones;
create policy "Users can delete own milestones"
on public.milestones
for delete
to authenticated
using (public.is_project_owner(project_id));

-- ============================================================
-- JOURNAL POLICIES
-- ============================================================

drop policy if exists "Users can view own journal entries" on public.journal_entries;
create policy "Users can view own journal entries"
on public.journal_entries
for select
to authenticated
using (public.is_project_owner(project_id));

drop policy if exists "Users can create own journal entries" on public.journal_entries;
create policy "Users can create own journal entries"
on public.journal_entries
for insert
to authenticated
with check (public.is_project_owner(project_id));

drop policy if exists "Users can update own journal entries" on public.journal_entries;
create policy "Users can update own journal entries"
on public.journal_entries
for update
to authenticated
using (public.is_project_owner(project_id))
with check (public.is_project_owner(project_id));

drop policy if exists "Users can delete own journal entries" on public.journal_entries;
create policy "Users can delete own journal entries"
on public.journal_entries
for delete
to authenticated
using (public.is_project_owner(project_id));

-- ============================================================
-- PROJECT CHECK-INS POLICIES
-- ============================================================

drop policy if exists "Users can view own checkins" on public.project_checkins;
create policy "Users can view own checkins"
on public.project_checkins
for select
to authenticated
using (public.is_project_owner(project_id));

drop policy if exists "Users can create own checkins" on public.project_checkins;
create policy "Users can create own checkins"
on public.project_checkins
for insert
to authenticated
with check (public.is_project_owner(project_id));

drop policy if exists "Users can update own checkins" on public.project_checkins;
create policy "Users can update own checkins"
on public.project_checkins
for update
to authenticated
using (public.is_project_owner(project_id))
with check (public.is_project_owner(project_id));

drop policy if exists "Users can delete own checkins" on public.project_checkins;
create policy "Users can delete own checkins"
on public.project_checkins
for delete
to authenticated
using (public.is_project_owner(project_id));

-- ============================================================
-- MEDIA POLICIES
-- ============================================================

drop policy if exists "Users can view own media" on public.media;
create policy "Users can view own media"
on public.media
for select
to authenticated
using (user_id = auth.uid());

drop policy if exists "Users can create own media" on public.media;
create policy "Users can create own media"
on public.media
for insert
to authenticated
with check (
    user_id = auth.uid()
    and public.is_project_owner(project_id)
    and (
        goal_id is null
        or public.is_goal_owner(goal_id)
    )
);

drop policy if exists "Users can update own media" on public.media;
create policy "Users can update own media"
on public.media
for update
to authenticated
using (user_id = auth.uid())
with check (
    user_id = auth.uid()
    and public.is_project_owner(project_id)
    and (
        goal_id is null
        or public.is_goal_owner(goal_id)
    )
);

drop policy if exists "Users can delete own media" on public.media;
create policy "Users can delete own media"
on public.media
for delete
to authenticated
using (user_id = auth.uid());

-- ============================================================
-- ACHIEVEMENTS POLICIES
-- ============================================================

drop policy if exists "Anyone can view achievements" on public.achievements;
create policy "Anyone can view achievements"
on public.achievements
for select
to anon, authenticated
using (true);

-- Achievements are managed by backend/admin.

-- ============================================================
-- USER ACHIEVEMENTS POLICIES
-- ============================================================

drop policy if exists "Users can view own achievements" on public.user_achievements;
create policy "Users can view own achievements"
on public.user_achievements
for select
to authenticated
using (user_id = auth.uid());

drop policy if exists "Users can unlock own achievements" on public.user_achievements;
create policy "Users can unlock own achievements"
on public.user_achievements
for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists "Users can delete own achievements" on public.user_achievements;
create policy "Users can delete own achievements"
on public.user_achievements
for delete
to authenticated
using (user_id = auth.uid());

-- ============================================================
-- PROJECT TEMPLATES POLICIES
-- ============================================================

drop policy if exists "Users can view public templates" on public.project_templates;
create policy "Users can view public templates"
on public.project_templates
for select
to anon, authenticated
using (
    is_public = true
    or created_by = auth.uid()
);

drop policy if exists "Users can create own templates" on public.project_templates;
create policy "Users can create own templates"
on public.project_templates
for insert
to authenticated
with check (created_by = auth.uid());

drop policy if exists "Users can update own templates" on public.project_templates;
create policy "Users can update own templates"
on public.project_templates
for update
to authenticated
using (created_by = auth.uid())
with check (created_by = auth.uid());

drop policy if exists "Users can delete own templates" on public.project_templates;
create policy "Users can delete own templates"
on public.project_templates
for delete
to authenticated
using (created_by = auth.uid());

-- ============================================================
-- NOTIFICATIONS POLICIES
-- ============================================================

drop policy if exists "Users can view own notifications" on public.notifications;
create policy "Users can view own notifications"
on public.notifications
for select
to authenticated
using (user_id = auth.uid());

drop policy if exists "Users can create own notifications" on public.notifications;
create policy "Users can create own notifications"
on public.notifications
for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists "Users can update own notifications" on public.notifications;
create policy "Users can update own notifications"
on public.notifications
for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists "Users can delete own notifications" on public.notifications;
create policy "Users can delete own notifications"
on public.notifications
for delete
to authenticated
using (user_id = auth.uid());

-- ============================================================
-- END RLS
-- ============================================================
